# 多元线性回归的实现

In [1]:
import numpy as np
from matplotlib import pyplot as plt
from sklearn import datasets

In [2]:
boston = datasets.load_boston()

X = boston.data
y = boston.target

X = X[y < 50.0]
y = y[y < 50.0]

In [3]:
X.shape

(490, 13)

In [4]:
from myscript.train_test_split import train_test_split

In [5]:
X_train, y_train, X_test, y_test = train_test_split(X, y, seed=666)

In [6]:
X_train.shape

(392, 13)

In [7]:
X_test.shape

(98, 13)

In [8]:
from myscript.LinearRegression import LinearRegression

In [9]:
reg = LinearRegression()

In [10]:
reg.fit_normal(X_train, y_train)

LinearRegression()

In [11]:
reg.coef_

array([-1.18919477e-01,  3.63991462e-02, -3.56494193e-02,  5.66737830e-02,
       -1.16195486e+01,  3.42022185e+00, -2.31470282e-02, -1.19509560e+00,
        2.59339091e-01, -1.40112724e-02, -8.36521175e-01,  7.92283639e-03,
       -3.81966137e-01])

In [12]:
reg.intercetion_

34.16143549623827

In [13]:
# reg.predict(X_test)

In [14]:
reg.score(X_test, y_test)

0.81298026026586

# sklearn中是如何解决回归的·

In [15]:
from sklearn.linear_model import LinearRegression

In [16]:
lin_reg = LinearRegression()

In [17]:
X_train.shape

(392, 13)

In [18]:
X_test.shape

(98, 13)

In [19]:
lin_reg.fit(X_train, y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [20]:
lin_reg.coef_

array([-1.18919477e-01,  3.63991462e-02, -3.56494193e-02,  5.66737830e-02,
       -1.16195486e+01,  3.42022185e+00, -2.31470282e-02, -1.19509560e+00,
        2.59339091e-01, -1.40112724e-02, -8.36521175e-01,  7.92283639e-03,
       -3.81966137e-01])

In [21]:
lin_reg.intercept_

34.16143549624624

In [22]:
lin_reg.score(X_test, y_test)

0.8129802602658494

# 参数的可解释性

In [23]:
lin_reg.coef_

array([-1.18919477e-01,  3.63991462e-02, -3.56494193e-02,  5.66737830e-02,
       -1.16195486e+01,  3.42022185e+00, -2.31470282e-02, -1.19509560e+00,
        2.59339091e-01, -1.40112724e-02, -8.36521175e-01,  7.92283639e-03,
       -3.81966137e-01])

In [24]:
np.argsort(lin_reg.coef_)

array([ 4,  7, 10, 12,  0,  2,  6,  9, 11,  1,  3,  8,  5], dtype=int64)

In [25]:
boston.feature_names

array(['CRIM', 'ZN', 'INDUS', 'CHAS', 'NOX', 'RM', 'AGE', 'DIS', 'RAD',
       'TAX', 'PTRATIO', 'B', 'LSTAT'], dtype='<U7')

In [26]:
print(boston.DESCR)


Boston House Prices dataset

Notes
------
Data Set Characteristics:  

    :Number of Instances: 506 

    :Number of Attributes: 13 numeric/categorical predictive
    
    :Median Value (attribute 14) is usually the target

    :Attribute Information (in order):
        - CRIM     per capita crime rate by town
        - ZN       proportion of residential land zoned for lots over 25,000 sq.ft.
        - INDUS    proportion of non-retail business acres per town
        - CHAS     Charles River dummy variable (= 1 if tract bounds river; 0 otherwise)
        - NOX      nitric oxides concentration (parts per 10 million)
        - RM       average number of rooms per dwelling
        - AGE      proportion of owner-occupied units built prior to 1940
        - DIS      weighted distances to five Boston employment centres
        - RAD      index of accessibility to radial highways
        - TAX      full-value property-tax rate per $10,000
        - PTRATIO  pupil-teacher ratio by town
      

# KNNRegressor

In [27]:
from sklearn.preprocessing import StandardScaler
standardScaler = StandardScaler()

In [28]:
standardScaler.fit(X_train,y_train)

StandardScaler(copy=True, with_mean=True, with_std=True)

In [29]:
X_train_standard = standardScaler.transform(X_train)

In [30]:
X_test_standard = standardScaler.transform(X_test)

In [31]:
from sklearn.neighbors import KNeighborsRegressor

In [32]:
knn_reg = KNeighborsRegressor()

In [34]:
knn_reg.fit(X_train_standard, y_train)

KNeighborsRegressor(algorithm='auto', leaf_size=30, metric='minkowski',
          metric_params=None, n_jobs=1, n_neighbors=5, p=2,
          weights='uniform')

In [35]:
knn_reg.score(X_test_standard, y_test)

0.846645115303895

In [36]:
from sklearn.model_selection import GridSearchCV

In [37]:
param_gird =[
    {
        'weights':['uniform'],
        'n_neighbors':[i for i in range(1, 11)]
    }, 
    {
        'weights':['distance'],
        'n_neighbors':[i for i in range(1, 11)],
        'p':[i for i in range(1, 6)]
    }, 
]

In [38]:
knn_reg2 = KNeighborsRegressor()

In [40]:
grid_SearchCV = GridSearchCV(knn_reg2, param_gird,n_jobs=-1, verbose=1)

In [41]:
grid_SearchCV.fit(X_train_standard, y_train)

Fitting 3 folds for each of 60 candidates, totalling 180 fits


[Parallel(n_jobs=-1)]: Done  34 tasks      | elapsed:    3.9s
[Parallel(n_jobs=-1)]: Done 180 out of 180 | elapsed:    4.8s finished


GridSearchCV(cv=None, error_score='raise',
       estimator=KNeighborsRegressor(algorithm='auto', leaf_size=30, metric='minkowski',
          metric_params=None, n_jobs=1, n_neighbors=5, p=2,
          weights='uniform'),
       fit_params=None, iid=True, n_jobs=-1,
       param_grid=[{'weights': ['uniform'], 'n_neighbors': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]}, {'weights': ['distance'], 'n_neighbors': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10], 'p': [1, 2, 3, 4, 5]}],
       pre_dispatch='2*n_jobs', refit=True, return_train_score='warn',
       scoring=None, verbose=1)

In [42]:
grid_SearchCV.best_params_

{'n_neighbors': 5, 'p': 1, 'weights': 'distance'}

In [43]:
grid_SearchCV.best_score_

0.799179998909969

In [47]:
grid_SearchCV.best_estimator_.score(X_test_standard, y_test)

0.880996650994177