# 使用sklearn中的knn算法

In [1]:
import numpy as np
from matplotlib import pyplot as plt

In [2]:
# from sklearn import datasets
# 导入
from sklearn.neighbors import KNeighborsClassifier

In [3]:
# 实例化
kNN_classifier = KNeighborsClassifier(n_neighbors=6)

In [4]:
# 数据
# 特征
raw_data_x= [[3.393533211,2.331273381],
             [2.110073483,1.781539638],
             [1.343808831,3.368360954],
             [3.582294042,4.679179110],
             [2.280362439,2.866990263],
             [7.423436942,4.696522875],
             [5.745051997,3.533989803],
             [9.172168622,2.511101045],
             [7.792783481,3.424088941],
             [7.939820817,0.791637231]
            ]
# 所属类别
raw_data_y = [0,0,0,0,0,1,1,1,1,1]
x = np.array([8.09121212,3.3545454545])
X_train = np.array(raw_data_x)
y_train = np.array(raw_data_y)

In [5]:
kNN_classifier.fit(X_train, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=6, p=2,
           weights='uniform')

In [6]:
x = x.reshape(1,-1)
x

array([[8.09121212, 3.35454545]])

In [7]:
y_predict = kNN_classifier.predict(x)
y_predict

array([1])

In [8]:
y_predict[0]

1

### JUPYTER 的魔法命令 %run

In [9]:
%run myscript/hello.py

hello.py被调用


In [10]:
hello('eric')

hello eric


In [11]:
from myscript import hello

hello.py被调用


In [12]:
hello.hello('haha')

hello haha


# 像Sklearn 的模式一样封装KNN算法

In [13]:
# %run myscript/KNeighborsClassifier.py

In [14]:
from myscript.KNeighborsClassifier import KNeighborsClassifier

In [15]:
kNeighborsClassifier = KNeighborsClassifier(6)

In [16]:
kNeighborsClassifier.fit(X_train, y_train)

In [17]:
kNeighborsClassifier.predict(x)

array([1])